using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// BossStraightGazeTracker
/// - Tracks the straight connector segments generated by StraightPathGenerator.
/// - User must clear segments in order from START marker to endpoint.
/// - Notifies BossMiniGame (owner.ConnectorCleared) when the connector is fully cleared.
/// - Middle segments are released back to StraightPathGenerator's pool instead of destroyed.
/// </summary>
public class BossStraightGazeTracker : MonoBehaviour
{
    [Tooltip("The StraightPathGenerator instance that produced the UI for the current connector.")]
    public StraightPathGenerator straightGenerator;

    [Tooltip("The gaze dot (must have dotRect assigned).")]
    public GazeDot gazeDot;

    [Tooltip("Owner to notify when the connector is cleared.")]
    public BossMiniGame owner;

    [Header("Per-segment SFX (per-line pitch ramp)")]
    public AudioClip lineClearClip;
    [Tooltip("Base pitch for the first cleared segment (usually 1.0)")]
    public float lineBasePitch = 1.0f;
    [Tooltip("Pitch step added for each subsequent cleared segment")]
    public float linePitchStep = 0.05f;
    [Tooltip("Maximum allowed pitch")]
    public float lineMaxPitch = 2.0f;
    [Range(0f, 1f)]
    public float lineSfxVolume = 0.8f;

    // runtime
    private bool tracking = false;
    public bool trackingPaused = false;

    private List<bool> groupStarted;
    private int patternHitCount = 0;
    private int patternTotalCount = 0;

    // per-group cleared counts for pitch ramping
    private List<int> groupClearCounts;

    // avoid double completion
    private bool completionNotified = false;

    // cached corner arrays (avoid allocations every frame)
    private readonly Vector3[] _dotCorners = new Vector3[4];
    private readonly Vector3[] _tmpCorners = new Vector3[4];

    private void Awake()
    {
        if (straightGenerator == null)
        {
            Debug.LogWarning("[BossStraightGazeTracker] straightGenerator is not assigned.");
        }
        if (gazeDot == null)
        {
            Debug.LogWarning("[BossStraightGazeTracker] gazeDot is not assigned.");
        }
        if (owner == null)
        {
            Debug.LogWarning("[BossStraightGazeTracker] owner is not assigned (BossMiniGame).");
        }
    }

    /// <summary>
    /// Start tracking the current straightGenerator UI.
    /// Safe even if generator hasn't produced UI yet; Update will wait.
    /// </summary>
    public void StartTracking()
    {
        if (straightGenerator == null)
        {
            Debug.LogWarning("[BossStraightGazeTracker] StartTracking called but straightGenerator is null.");
            return;
        }

        if (gazeDot == null)
        {
            Debug.LogWarning("[BossStraightGazeTracker] StartTracking called but gazeDot is null.");
            return;
        }

        tracking = true;
        trackingPaused = false;
        completionNotified = false;

        groupStarted = null;
        patternHitCount = 0;
        patternTotalCount = 0;
        groupClearCounts = null;
    }

    private void Update()
    {
        if (!tracking || straightGenerator == null || gazeDot == null) return;
        if (trackingPaused) return;

        // Ensure generator has at least one group.
        if ((straightGenerator.segmentGroups == null || straightGenerator.segmentGroups.Count == 0) &&
            (straightGenerator.segments != null && straightGenerator.segments.Count > 0))
        {
            straightGenerator.segmentGroups = new List<List<RectTransform>>();
            var fallback = new List<RectTransform>(straightGenerator.segments);
            straightGenerator.segmentGroups.Add(fallback);
        }

        int groupCount = (straightGenerator.segmentGroups != null) ? straightGenerator.segmentGroups.Count : 0;
        int flatCount = (straightGenerator.segments != null) ? straightGenerator.segments.Count : 0;

        // Still nothing spawned, just wait.
        if (groupCount == 0 && flatCount == 0)
        {
            return;
        }

        // Initialize state once, after generator has data.
        if (groupStarted == null)
        {
            groupStarted = new List<bool>(groupCount);
            groupClearCounts = new List<int>(groupCount);
            patternTotalCount = 0;

            for (int g = 0; g < groupCount; g++)
            {
                groupStarted.Add(false);
                groupClearCounts.Add(0);

                List<RectTransform> grp = straightGenerator.segmentGroups[g];
                if (grp != null)
                {
                    patternTotalCount += grp.Count;
                }
            }
        }

        RectTransform dotRect = gazeDot.dotRect;
        if (dotRect == null) return;

        dotRect.GetWorldCorners(_dotCorners);
        Rect dotScreenRect = new Rect(_dotCorners[0], _dotCorners[2] - _dotCorners[0]);

        List<List<RectTransform>> groups = straightGenerator.segmentGroups;
        List<RectTransform> startRects = straightGenerator.startPointRects;
        List<RectTransform> endRects = straightGenerator.endPointRects;

        // 1) Start markers: touching a start activates that group.
        for (int g = 0; g < groupCount; g++)
        {
            if (groupStarted == null || g >= groupStarted.Count) break;
            if (groupStarted[g]) continue;

            RectTransform startRect = null;
            if (startRects != null && g < startRects.Count)
            {
                startRect = startRects[g];
            }

            if (startRect == null) continue;

            startRect.GetWorldCorners(_tmpCorners);
            Rect startScreenRect = new Rect(_tmpCorners[0], _tmpCorners[2] - _tmpCorners[0]);

            if (dotScreenRect.Overlaps(startScreenRect))
            {
                groupStarted[g] = true;

                // START marker is not pooled
                Destroy(startRect.gameObject);
                if (straightGenerator.startPointRects != null && g < straightGenerator.startPointRects.Count)
                {
                    straightGenerator.startPointRects[g] = null;
                }

                if (groupClearCounts != null && g < groupClearCounts.Count)
                {
                    groupClearCounts[g] = 0;
                }
            }
        }

        // 2) Sequential clearing per active group (always group[0] first)
        for (int g = 0; g < groupCount; g++)
        {
            if (groupStarted == null || g >= groupStarted.Count) continue;
            if (!groupStarted[g]) continue;

            List<RectTransform> group = groups[g];
            if (group == null || group.Count == 0) continue;

            RectTransform nextSeg = group[0];
            if (nextSeg == null)
            {
                group.RemoveAt(0);
                continue;
            }

            nextSeg.GetWorldCorners(_tmpCorners);
            Rect segScreenRect = new Rect(_tmpCorners[0], _tmpCorners[2] - _tmpCorners[0]);

            if (dotScreenRect.Overlaps(segScreenRect))
            {
                patternHitCount++;

                // Remove from flat list if present
                if (straightGenerator.segments != null)
                {
                    for (int s = straightGenerator.segments.Count - 1; s >= 0; s--)
                    {
                        if (straightGenerator.segments[s] == nextSeg)
                        {
                            straightGenerator.segments.RemoveAt(s);
                            break;
                        }
                    }
                }

                // Release/destroy segment through generator (middle segments are pooled)
                straightGenerator.ReleaseOrDestroySegment(nextSeg.gameObject);

                // Per-group clear counter for pitch ramp
                if (groupClearCounts != null && g < groupClearCounts.Count)
                {
                    groupClearCounts[g]++;
                    int cleared = groupClearCounts[g];

                    float pitch = lineBasePitch + linePitchStep * (cleared - 1);
                    pitch = Mathf.Min(pitch, lineMaxPitch);

                    if (lineClearClip != null)
                    {
                        SoundManager.PlaySFXWithPitch(lineClearClip, pitch, lineSfxVolume);
                    }
                    else
                    {
                        SoundManager.PlaySFX(SoundType.Touch, lineSfxVolume);
                    }
                }
                else
                {
                    if (lineClearClip != null)
                    {
                        SoundManager.PlaySFXWithPitch(lineClearClip, lineBasePitch, lineSfxVolume);
                    }
                    else
                    {
                        SoundManager.PlaySFX(SoundType.Touch, lineSfxVolume);
                    }
                }

                group.RemoveAt(0);
            }
        }

        // 3) Completion check
        bool allGroupsEmpty = true;
        if (groups != null)
        {
            foreach (List<RectTransform> g in groups)
            {
                if (g != null && g.Count > 0)
                {
                    allGroupsEmpty = false;
                    break;
                }
            }
        }

        // Endpoints: only allow finishing if all groups empty.
        if (endRects != null)
        {
            for (int e = 0; e < endRects.Count; e++)
            {
                RectTransform endRect = endRects[e];
                if (endRect == null) continue;

                endRect.GetWorldCorners(_tmpCorners);
                Rect endScreenRect = new Rect(_tmpCorners[0], _tmpCorners[2] - _tmpCorners[0]);

                if (dotScreenRect.Overlaps(endScreenRect))
                {
                    if (allGroupsEmpty)
                    {
                        StartCompletion();
                        return;
                    }
                }
            }
        }

        if (allGroupsEmpty)
        {
            StartCompletion();
        }
    }

    private void StartCompletion()
    {
        if (completionNotified) return;

        completionNotified = true;
        tracking = false;

        StartCoroutine(DelayedNotifyAndReset());
    }

    /// <summary>
    /// Wait one frame to let the generator / mini-game cleanup complete,
    /// then notify the owner and reset.
    /// </summary>
    private IEnumerator DelayedNotifyAndReset()
    {
        yield return null;

        if (owner != null)
        {
            try
            {
                owner.ConnectorCleared();
            }
            catch (System.Exception ex)
            {
                Debug.LogWarning("[BossStraightGazeTracker] owner.ConnectorCleared() threw: " + ex.Message);
            }
        }
        else
        {
            Debug.LogWarning("[BossStraightGazeTracker] No owner assigned to notify.");
        }

        Reset();
    }

    public void Reset()
    {
        tracking = false;
        trackingPaused = false;
        completionNotified = false;

        if (straightGenerator != null)
        {
            straightGenerator.ClearExisting();
        }

        groupStarted = null;
        groupClearCounts = null;
        patternHitCount = 0;
        patternTotalCount = 0;
    }

    public void StopTracking()
    {
        tracking = false;
        Reset();
    }
}
